/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health check */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Service is up */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example ok */
                            status: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/teams": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all teams */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description All 32 NFL teams */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Team"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/teams/{abbreviation}/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Weekly efficiency trend for one team */
        get: {
            parameters: {
                query?: {
                    /** @description Defaults to the most recent season with data */
                    season?: components["parameters"]["Season"];
                };
                header?: never;
                path: {
                    /** @example KC */
                    abbreviation: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Team info plus one row per week played */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            team: components["schemas"]["Team"];
                            season: number;
                            weeks: components["schemas"]["TeamWeekMetrics"][];
                        };
                    };
                };
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/compare": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Side-by-side weekly series and season averages for two teams */
        get: {
            parameters: {
                query: {
                    /** @example KC */
                    teamA: string;
                    /** @example BUF */
                    teamB: string;
                    /** @description Defaults to the most recent season with data */
                    season?: components["parameters"]["Season"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Both teams' weekly series and season averages */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            season: number;
                            teamA: components["schemas"]["TeamComparison"];
                            teamB: components["schemas"]["TeamComparison"];
                        };
                    };
                };
                400: components["responses"]["BadRequest"];
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/leaderboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Teams ranked by one efficiency metric */
        get: {
            parameters: {
                query?: {
                    /** @description Defaults to epa_per_play */
                    metric?: components["schemas"]["MetricColumn"];
                    order?: "asc" | "desc";
                    limit?: number;
                    /** @description Defaults to the most recent season with data */
                    season?: components["parameters"]["Season"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Teams ranked by the requested metric */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["LeaderboardEntry"][];
                    };
                };
                /** @description Invalid metric name (whitelist-checked before use in SQL) */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/predictions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Win probabilities for one week's games
         * @description Defaults to the earliest (season, week) with at least one game that hasn't been played yet.
         */
        get: {
            parameters: {
                query?: {
                    /** @description Defaults to the most recent season with data */
                    season?: components["parameters"]["Season"];
                    week?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Games for the resolved season/week, with predictions where available */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            season: number | null;
                            week: number | null;
                            games: components["schemas"]["GamePrediction"][];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/players": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Qualifying starters at one position, ranked by a metric
         * @description "Starter" is approximated by a minimum-volume cutoff (no snap-count data available) — see each position's metric definitions. Always returns every metric defined for the position in `values`, not just the one sorted on, so a future two-metric view needs no API change.
         */
        get: {
            parameters: {
                query: {
                    position: components["schemas"]["PositionGroup"];
                    /** @description Defaults to the position's first metric. Must be one of that position's own metrics. */
                    metric?: string;
                    order?: "asc" | "desc";
                    limit?: number;
                    /** @description Defaults to the most recent season with data */
                    season?: components["parameters"]["Season"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Qualifying players at the position, with every metric for that position */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            position: components["schemas"]["PositionGroup"];
                            season: number;
                            metrics: string[];
                            players: components["schemas"]["PlayerMetricEntry"][];
                        };
                    };
                };
                /** @description Invalid position, or a metric not defined for that position */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Error: {
            error: string;
        };
        Team: {
            id: number;
            name: string;
            abbreviation: string;
            conference: string | null;
            division: string | null;
            logo_url: string | null;
            /** @description Primary team color, hex */
            color: string | null;
            /** @description Secondary team color, hex */
            color2: string | null;
        };
        /** @enum {string} */
        MetricColumn: "epa_per_play" | "success_rate" | "points_per_drive" | "epa_per_play_allowed" | "success_rate_allowed" | "points_per_drive_allowed" | "st_epa_per_play" | "st_epa_per_play_allowed";
        TeamWeekMetrics: {
            week: number;
            epa_per_play: number | null;
            success_rate: number | null;
            points_per_drive: number | null;
            epa_per_play_allowed: number | null;
            success_rate_allowed: number | null;
            points_per_drive_allowed: number | null;
            st_epa_per_play: number | null;
            st_epa_per_play_allowed: number | null;
        };
        TeamComparison: {
            team: components["schemas"]["Team"];
            weeks: components["schemas"]["TeamWeekMetrics"][];
            /** @description Season-long average of each metric, keyed by MetricColumn */
            averages: {
                [key: string]: number | null;
            };
        };
        LeaderboardEntry: {
            abbreviation: string;
            name: string;
            value: number;
            logo_url: string | null;
            /** @description Primary team color, hex */
            color: string | null;
        };
        GamePrediction: {
            game_id: string;
            season: number;
            week: number;
            /** Format: date */
            date: string;
            home_team: string;
            home_team_name: string;
            away_team: string;
            away_team_name: string;
            home_score: number | null;
            away_score: number | null;
            home_win_probability: number | null;
        };
        /** @enum {string} */
        PositionGroup: "QB" | "RB" | "WR" | "TE" | "EDGE" | "LB" | "CB" | "S";
        PlayerMetricEntry: {
            player_id: string;
            name: string;
            headshot_url: string | null;
            /** @description The stat this position's starter cutoff is measured on (e.g. attempts for QB, games for EDGE) */
            volume: number;
            team_abbreviation: string;
            team_color: string | null;
            team_logo_url: string | null;
            /** @description Every metric defined for this position, keyed by metric name */
            values: {
                [key: string]: number | null;
            };
        };
    };
    responses: {
        /** @description No team with that abbreviation */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Missing or invalid query parameter */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: {
        /** @description Defaults to the most recent season with data */
        Season: number;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
